import { Metadata } from "next";
import { DotPattern } from "@/components/ui/dot-pattern";

export const metadata: Metadata = {
  title: "Portfolio Resume",
  description: "Generated by Portfolio Resume",
};

function ResumeLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen">
      <DotPattern />
      <div className="relative z-10">{children}</div>
    </div>
  );
}

export default ResumeLayout;
